### PR TITLE
Added missing translation for Duke Eltan answer.

### PR DESCRIPTION
**Pull request by Roberciiik**

### CODE REVIEW

**Comment by SkushaKutusha** [comment]
Here is russian translation for Duke Eltan answer.
@71 = ~Хорошего дня.~

**Comment by Gitjas** [comment]
@Roberciiik  thank you very much!

@SkushaKutusha unfortunately I cannot copy&paste cyrillic letters, I'd need a pull request to integrate a Russian translation. Thank you nontheless.

**Comment by Roberciiik** [comment]
@Gitjas @SkushaKutusha 
I included russian line in my pull request taken from another strref. Cannot be used here?
`@71  = ~Приятного тебе дня.~`

**Comment by SkushaKutusha** [comment]
Yeah, that's fine too. Thank you!

**Comment by Gitjas** [comment]
@Roberciiik @SkushaKutusha sorry, I replaced your translation Robrciiik with what yota13 posted at G3 on my fork because I thought yours need to be corrected. (No Russian speaker here. :-( )

**Comment by Roberciiik** [comment]
@Gitjas Yeah, you're right, I can't speak Russian and I should note that these translations are copied from existing game resources. I also checked them in translator for sure.

**Pull request merged**
